version: '3.1'

services:
  hhn-welcome-frontend:
    build:
      context: hhn-welcome
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    restart: always
